;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-insert-left-brace
        TeX-font
        TeX-insert-backslash
        TeX-insert-macro
        counsel-M-x
        end-of-visual-line
        markdown-outdent-or-delete
        ))

(setq mc/cmds-to-run-once
      '(
        mouse-wheel-text-scale
        ))
