;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-insert-left-brace
        TeX-font
        TeX-insert-backslash
        TeX-insert-macro
        end-of-visual-line
        markdown-outdent-or-delete
        mouse-save-then-kill
        nv-delete-back-all
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        org-shiftcontrolright
        rectangle-mark-mode
        toggle-frame-fullscreen
        undo-only
        ))

(setq mc/cmds-to-run-once
      '(
        handle-switch-frame
        ))
