;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-insert-item
        LaTeX-insert-left-brace
        TeX-insert-backslash
        TeX-insert-macro
        dired-toggle-read-only
        end-of-visual-line
        multiple-cursors-mode
        org-self-insert-command
        yank
        ))
